image:
  repository: jhonderson/actual-http-api
  pullPolicy: IfNotPresent
  tag: v0.14.0@sha256:3afb343b852c5d36aa000b5eb4964a2da3c65c90aa36ba7ba7d4f8d79ef8a88a

TZ: America/Santiago

portal:
  open:
    enabled: true
persistence:
  data:
    enabled: true
    retain: true
    mountPath: /data
service:
  main:
    ports:
      main:
        port: 10121
        targetPort: 5007
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
