image:
  repository: ghcr.io/cheshire-cat-ai/core
  pullPolicy: IfNotPresent
  tag: 1.7.1@sha256:22b6a6558616bff9026437fda5fabb3ccfc82dddb023d53309725b931deb0401

TZ: America/Santiago

portal:
  open:
    enabled: true
persistence:
  static:
    enabled: true
    retain: true
    mountPath: /app/cat/static
  plugins:
    enabled: true
    retain: true
    mountPath: /app/cat/plugins
  data:
    enabled: true
    retain: true
    mountPath: /app/cat/data
service:
  main:
    ports:
      main:
        port: 10120
        targetPort: 80
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
