image:
  repository: ghcr.io/patricioperezv/rathena-server-pec/rathena
  pullPolicy: IfNotPresent
  tag: c313602b06f6c64fc22da13b2f72079aafbcf103@sha256:b8a7034e6da2b7887bad4c46299ed9e1ce28aee17c4a5b681771167d5f0aa2c2

TZ: America/Santiago

mariadb:
  enabled: true
  mariadbDatabase: rathena
  rathenaImage:
    repository: ghcr.io/patricioperezv/rathena-server-pec/rathena
    pullPolicy: IfNotPresent
    tag: c313602b06f6c64fc22da13b2f72079aafbcf103@sha256:b8a7034e6da2b7887bad4c46299ed9e1ce28aee17c4a5b681771167d5f0aa2c2
  persistence:
    data:
      retain: true
    sql-files:
      enabled: true
      type: emptyDir
      mountPath: /docker-entrypoint-startdb.d
      targetSelectAll: true
    post-deployment-sql:
      enabled: true
      type: secret
      objectName: rathena
      expandObjectName: false
      items:
        - key: updateInterServerPasswordSql
          path: z999999-update-inter-server-password.sql
      mountPath: /post-deployment-sql
      targetSelectAll: true
      readOnly: true
  workload:
    main:
      podSpec:
        initContainers:
          initial-sql:
            enabled: true
            type: install
            imageSelector: rathenaImage
            command: ["/bin/bash", "-c"]
            args: ["cp -rL /rathena/sql-files/* /docker-entrypoint-startdb.d && cp -rL /post-deployment-sql/* /docker-entrypoint-startdb.d"]
portal:
  open:
    enabled: false
persistence:
  inter-conf:
    enabled: true
    type: secret
    objectName: rathena
    expandObjectName: false
    items:
      - key: interConf
        path: inter_conf.txt
      - key: charConf
        path: char_conf.txt
      - key: mapConf
        path: map_conf.txt
    mountPath: /rathena/conf/import
    readOnly: true
    targetSelectAll: true
service:
  main:
    enabled: false
  login:
    enabled: true
    primary: true
    ports:
      login:
        enabled: true
        primary: true
        port: 6900
  char:
    enabled: true
    targetSelector: char
    ports:
      char:
        enabled: true
        primary: true
        port: 6121
  map:
    enabled: true
    targetSelector: map
    ports:
      map:
        enabled: true
        primary: true
        port: 5121
workload:
  main:
    enabled: false
  login:
    enabled: true
    primary: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          stdin: true
          tty: true
          command: ["/bin/bash", "-c"]
          args: ["/rathena/login-server"]
          probes:
            liveness:
              enabled: true
              type: tcp
              port: 6900
              initialDelaySeconds: 10000
            readiness:
              enabled: true
              type: tcp
              port: 6900
              initialDelaySeconds: 10000
            startup:
              enabled: true
              type: tcp
              port: 6900
              initialDelaySeconds: 10000
  map:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          stdin: true
          tty: true
          command: ["/bin/bash", "-c"]
          args: ["/rathena/map-server"]
          probes:
            liveness:
              enabled: true
              type: tcp
              port: 5121
              initialDelaySeconds: 10000
            readiness:
              enabled: true
              type: tcp
              port: 5121
              initialDelaySeconds: 10000
            startup:
              enabled: true
              type: tcp
              port: 5121
              initialDelaySeconds: 10000
  char:
    enabled: true
    type: Deployment
    podSpec:
      containers:
        main:
          enabled: true
          primary: true
          stdin: true
          tty: true
          command: ["/bin/bash", "-c"]
          args: ["/rathena/char-server"]
          probes:
            liveness:
              enabled: true
              type: tcp
              port: 6121
              initialDelaySeconds: 10000
            readiness:
              enabled: true
              type: tcp
              port: 6121
              initialDelaySeconds: 10000
            startup:
              enabled: true
              type: tcp
              port: 6121
              initialDelaySeconds: 10000
